### ISSUE TITLE
propagating names from RangesList to GRanges

### ISSUE THREAD

**Issue by lawremi** [Bioconductor/GenomicRanges#15]
Should this give `"foo"` or `NULL` (as currently):

```
names(GRanges(IRangesList(chr1=IRanges(1, 10, names="foo"))))
```

**Comment by hpages** [comment]
@lawremi Are you planning to follow up on this or can we close the issue?

**Comment by lawremi** [comment]
I was just wondering about this in the abstract and thought it would be good to record it.  It sounds like you'd prefer it to be closed, so I'll go ahead and do that.

**Comment by hpages** [comment]
Thanks! If you're not going to do anything about this then there is no point in keeping the issue open. This coercion method is originally yours. Feel free to improve it as you wish. I already added a note in the source code many years ago about the names and metadata columns not being propagated https://github.com/Bioconductor/GenomicRanges/blob/550a4794511968d9b2a65fd269cc329ae94af831/R/GRanges-class.R#L337-L357 I don't feel that we also need to record this as an issue unless you feel it's actually an issue but it doesn't seem so.
