### ISSUE TITLE
annoying warning when `as.data.frame(..., stringsAsFactors=F)`-ing on GRanges object

### ISSUE THREAD

**Issue by gwangjinkim** [Bioconductor/GenomicRanges#18]
```
require(GenomicRanges)
g1 <- GRanges(data.frame(seqnames="Chr1",
                         strand="+",
                         start=c(2,2,2,4,5,6),
                         end=c(24,25,25,25,25,21),
                         m1=c("a","a","a","b","b","b"),
                         m2=c("A","B","A","B","A","B"),
                         m3=c(1,2,3,4,5,6), stringsAsFactors=F))
as.data.frame(g1, stringsAsFactors=F)
##   seqnames start end width strand m1 m2 m3
## 1     Chr1     2  24    23      +  a  A  1
## 2     Chr1     2  25    24      +  a  B  2
## 3     Chr1     2  25    24      +  a  A  3
## 4     Chr1     4  25    22      +  b  B  4
## 5     Chr1     5  25    21      +  b  A  5
## 6     Chr1     6  21    16      +  b  B  6
## Warning message:
## In as.data.frame(mcols(x), ...) : Arguments in '...' ignored
```

The warning message is annoying, and by the way, the default behaviour is `stringsAsFactors=F`.
So why not disabling it when `stringsAsFactors=F`?
For the case `stringsAsFactors=T`, the warning might be good to know.

**Comment by lawremi** [comment]
We should probably add `stringsAsFactors=FALSE` to the formals of `as.data.frame,DataFrame()` and assert that `stringsAsFactors` is `FALSE`. That way it's self-documenting, and any attempt to do the opposite results in an error, not just a warning.

**Comment by lawremi** [comment]
No, I don't think so. I guess one could add `stringsAsFactors` to its formals also, but ...

**Comment by lawremi** [comment]
This is fixed in S4Vectors 0.19.24.

**Comment by gwangjinkim** [comment]
hm what you mean wtiht he last sentence? - is it fixed in future version? Where one can see that it is fixed in S4 Vectors 0.18.24? Sorry for my ignorance ...

**Comment by lawremi** [comment]
Yes S4Vectors 0.19.24 will be available within a couple of days. Thanks for the report.

**Comment by gwangjinkim** [comment]
Ah okay, great! Thank you also, too!
