### ISSUE TITLE
Sorting a SortedByQueryHits produces a Hits

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/GenomicRanges#2]
Running the following code on the current _GenomicRanges_ devel version (1.31.3):

```r
library(GenomicRanges)
example(GenomicRanges, echo=FALSE)
olap <- findOverlaps(gr, gr)
class(sort(olap))
```

... gives a `Hits` object, while previously in the release (1.30.0) it gave a `SortedByQueryHits` object. Is this change intentional? I am curious because my _InteractionSet_ package defines its own `findOverlaps` method, and I would like to know what the correct return class should be.

**Comment by lawremi** [comment]
Sorry, my bad, I fixed this in S4Vectors
