### ISSUE TITLE
Export GenomicRanges object as gtf file

### ISSUE THREAD

**Issue by Roooosh** [Bioconductor/GenomicRanges#21]
Hello, 
I'm relatively new to working with GenomicRanges, so this question may be naive, but I couldn't find any documentation elsewhere.

I was wondering if it is possible to export the genomic ranges(Granges) object as a gtf(gene transfer format).

For my current analysis, it is important for me to identify exons that overlap between different genes in my reference annotation and exclude them. I did this by the following call:

no.overlappers <- exonicParts(eqcab_db, linked.to.single.gene.only=TRUE)

Now that I have dropped all of the exons that were linked to more than 1 gene, I'd like to export this file as a gtf for my analysis. Is this possible?

Thank you and let me know if there needs to be any further clarification. Look forward to your comments!

**Comment by PeteHaitch** [comment]
Yes, using `rtracklayer::export()`. 
Here is an example:

``` r
suppressPackageStartupMessages(library(rtracklayer))
# Get an example GRanges object
example("GRanges", echo = FALSE)
gr
#> GRanges object with 10 ranges and 2 metadata columns:
#>     seqnames    ranges strand |     score                GC
#>        <Rle> <IRanges>  <Rle> | <integer>         <numeric>
#>   a     chr2      1-10      - |         1                 1
#>   b     chr2      2-10      + |         2 0.888888888888889
#>   c     chr2      3-10      + |         3 0.777777777777778
#>   d     chr2      4-10      * |         4 0.666666666666667
#>   e     chr1      5-10      * |         5 0.555555555555556
#>   f     chr1      6-10      + |         6 0.444444444444444
#>   g     chr3      7-10      + |         7 0.333333333333333
#>   h     chr3      8-10      + |         8 0.222222222222222
#>   i     chr3      9-10      - |         9 0.111111111111111
#>   j     chr3        10      - |        10                 0
#>   -------
#>   seqinfo: 3 sequences from mock1 genome
export(gr, "~/tmp.gtf")
```

<sup>Created on 2019-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Then, from the terminal, we can see the output:

```sh
$ cat ~/tmp.gtf 
##gff-version 2
##source-version rtracklayer 1.42.1
##date 2019-01-30
##genome-build .	mock1
chr2	rtracklayer	sequence_feature	1	10	1	-	.	GC 1; ID "a"
chr2	rtracklayer	sequence_feature	2	10	2	+	.	GC 0.888888888888889; ID "b"
chr2	rtracklayer	sequence_feature	3	10	3	+	.	GC 0.777777777777778; ID "c"
chr2	rtracklayer	sequence_feature	4	10	4	.	.	GC 0.666666666666667; ID "d"
chr1	rtracklayer	sequence_feature	5	10	5	.	.	GC 0.555555555555556; ID "e"
chr1	rtracklayer	sequence_feature	6	10	6	+	.	GC 0.444444444444444; ID "f"
chr3	rtracklayer	sequence_feature	7	10	7	+	.	GC 0.333333333333333; ID "g"
chr3	rtracklayer	sequence_feature	8	10	8	+	.	GC 0.222222222222222; ID "h"
chr3	rtracklayer	sequence_feature	9	10	9	-	.	GC 0.111111111111111; ID "i"
chr3	rtracklayer	sequence_feature	10	10	10	-	.	GC 0; ID "j"
```

By the way, this type of question is better posted to https://support.bioconductor.org/ where more people will see it.
