### ISSUE TITLE
Feature request:  make mcols on a GRangesList return a SplitDataFrameList

### ISSUE THREAD

**Issue by FelixErnst** [Bioconductor/GenomicRanges#23]
I currently cannot access the metadata columns of GRangesList  without some form of custom "witchcraft"

```
library(TxDb.Scerevisiae.UCSC.sacCer3.sgdGene)
txdb <- TxDb.Scerevisiae.UCSC.sacCer3.sgdGene
grl<- GenomicFeatures::cdsBy(txdb, by = "gene")
mcols(grl)
#> DataFrame with 6534 rows and 0 columns
mcols(grl[[1]])
#> DataFrame with 2 rows and 2 columns
#>      cds_id    cds_name
#>   <integer> <character>
#> 1      6992          NA
#> 2      6993          NA
mcols(grl[,"cds_id"])
#> DataFrame with 6534 rows and 0 columns
```

For accessing columns my function looks like this
```
.get_column_GRangesList <- function(grl,column){
    relist(mcols(grl@unlistData)[,column],grl@partitioning)
}
```

Is there a specific reason, this feature exists as it is right now? Did I miss some specific way of accessing the metadata?

Thanks for any help and advice

**Comment by lawremi** [comment]
I think you are looking for `mcols(grl, level="within")`.

**Comment by FelixErnst** [comment]
Yes, indeed. Thanks for the advice. Would it be possible to add this to the man pages? Neither `?GRangesList` nor `?mcols` provides a hint about this argument.

**Comment by FelixErnst** [comment]
So I guess, an addition to the man pages regarding the `level` argument is not an option?
