### ISSUE TITLE
gpos/GPos equivalent for granges/GRanges

### ISSUE THREAD

**Issue by MalteThodberg** [Bioconductor/GenomicRanges#34]
Currently, calling granges on a GPos-object returns a GRanges-object. It would be nice if granges returned either the corresponding GPos-object, or adding a separate gpos function for the GPos class.

**Comment by hpages** [comment]
I think I will just make `granges()` return a GPos object. Will be consistent with `ranges()` returning an IPos object. Also that means we avoid the introduction of a new generic.

Thanks for your feedback.

**Comment by MalteThodberg** [comment]
Sounds great! I have closed the issue
