### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by xuebaliang** [Bioconductor/GenomicRanges#37]
Hello, I have installed the GenomicRanges of version 1.38 on my linux server. But when I import it, I get the following error:
> library(GenomicRanges)
Loading required package: BiocGenerics
Error in value[[3L]](cond) : 
  Package ‘BiocGenerics’ version 0.30.0 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘BiocGenerics’ is imported by ‘GenomicRanges’, ‘XVector’, ‘S4Vectors’, ‘GenomeInfoDb’, ‘IRanges’ so cannot be unloaded

How to fix this problem? I have installed BioGenerics of the newest version 0.32 from bioconductor. Thanks.

**Comment by hpages** [comment]
Looks like you might have a broken installation.

Please restart R and do the following:
```
library(BiocManager)
BiocManager::valid()
```
Follow any instruction given to you by `BiocManager::valid()`.

Then:
```
library(BiocGenerics)
library(S4Vectors)
library(IRanges)
library(GenomicRanges)
```

Show us **the full output** of all these commands.

Thanks!

**Comment by xuebaliang** [comment]
Thanks for your reply. I restart the R and run the import again, and it succeed. Thanks very much.
