### ISSUE TITLE
plan for dealing with loss of KEGG.db?

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/GenomicRanges#49]
KEGG.db is still in the DESCRIPTION file and used in vignettes.  Anyone planning on
revising package?  Ideally we would introduce values derived from KEGGREST.  If there
is no current plan I am willing to give this a shot in a PR.

**Comment by lshep** [comment]
I believe this was fixed with  https://github.com/Bioconductor/GenomicRanges/pull/50
