### ISSUE TITLE
Unexpected behavior of setdiff

### ISSUE THREAD

**Issue by gevro** [Bioconductor/GenomicRanges#62]
Hi,
Perhaps there is something fundamental I'm not understanding about setdiff, but it seems to be applying internally a 'reduce' command to the final output before outputting it.

Here is an example:
```
> input <- makeGRangesFromDataFrame(data.frame(chrom=c("chr1"),start=c(1,1,1,1,10,10,10,10),end=c(5,5,5,5,15,15,15,15)))
> input
GRanges object with 8 ranges and 0 metadata columns:
      seqnames    ranges strand
         <Rle> <IRanges>  <Rle>
  [1]     chr1       1-5      *
  [2]     chr1       1-5      *
  [3]     chr1       1-5      *
  [4]     chr1       1-5      *
  [5]     chr1     10-15      *
  [6]     chr1     10-15      *
  [7]     chr1     10-15      *
  [8]     chr1     10-15      *
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths


> filter <- makeGRangesFromDataFrame(data.frame(chrom=c("chr1"),start=10,end=15))
> filter
GRanges object with 1 range and 0 metadata columns:
      seqnames    ranges strand
         <Rle> <IRanges>  <Rle>
  [1]     chr1     10-15      *
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths


> setdiff(input,filter)
GRanges object with 1 range and 0 metadata columns:
      seqnames    ranges strand
         <Rle> <IRanges>  <Rle>
  [1]     chr1       1-5      *
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths
```
Why is the output of setdiff(input,filter) only produce 1 range? Shouldn't it produce 5 ranges, all chr1:1-5? Because the input had 5 ranges at chr1:1-5.

If this is the expected behavior of setdiff, I highly recommend to document this more clearly. And what would be the function to use that would produce the behavior I am looking for?

Thanks very much.

**Comment by gevro** [comment]
Is the correct function to use subsetByOverlaps(input,filter,invert=TRUE) ?

**Comment by hpages** [comment]
Hi,

The `union()`, `intersect()`, and `setdiff()` methods for GRanges objects interpret the two input GRanges objects as two _sets_ of genomic _positions_. In that context, a genomic _range_ is just a convenient way to represent a set of genomic _positions_. In other words, `GRanges(c("chr1: 25-50", "chr1:10-30"))` represents the same set of genomic positions as `GRanges("chr1:10-50")`, and, from a `setdiff()` point of view, they are the same. In other words, yes, everything happens as if `reduce()` was called on the input objects.

This follows the semantic of the `union()`, `intersect()`, and `setdiff()` methods for IRanges objects, which also treat the input objects as sets of individual positions. The man page for these methods says (`?IRanges::setdiff`): 

> The ‘union’, ‘intersect’ and ‘setdiff’ methods for IntegerRanges objects return a "normal"
> IntegerRanges object representing the union, intersection and (asymmetric!)  difference
> of the sets of integers represented by ‘x’ and ‘y’.

Maybe the man page for `GenomicRanges::setdiff()` should emphasize this.

If you want to remove the ranges in `input` that belong to `filter`, just do:
```
input[!(input %in% filter)]
# GRanges object with 4 ranges and 0 metadata columns:
#       seqnames    ranges strand
#          <Rle> <IRanges>  <Rle>
#   [1]     chr1       1-5      *
#   [2]     chr1       1-5      *
#   [3]     chr1       1-5      *
#   [4]     chr1       1-5      *
#   -------
#   seqinfo: 1 sequence from an unspecified genome; no seqlengths
```

If you want to keep the portion**s** of any range in `input` that do not overlap the ranges in `filter`, do:
```
input <- GRanges(c("chr1:1-50", "chr1:100-150", "chr1:40-110"))
filter <- GRanges(c("chr1:11-20", "chr1:90-105", "chrM:1-10", "chr1:55-60"))
psetdiff(input, rep(GRangesList(filter), length(input)))
# GRangesList object of length 3:
# [[1]]
# GRanges object with 2 ranges and 0 metadata columns:
#       seqnames    ranges strand
#          <Rle> <IRanges>  <Rle>
#   [1]     chr1      1-10      *
#   [2]     chr1     21-50      *
#   -------
#   seqinfo: 2 sequences from an unspecified genome; no seqlengths
# 
# [[2]]
# GRanges object with 1 range and 0 metadata columns:
#       seqnames    ranges strand
#          <Rle> <IRanges>  <Rle>
#   [1]     chr1   106-150      *
#   -------
#   seqinfo: 2 sequences from an unspecified genome; no seqlengths
# 
# [[3]]
# GRanges object with 2 ranges and 0 metadata columns:
#       seqnames    ranges strand
#          <Rle> <IRanges>  <Rle>
#   [1]     chr1     40-54      *
#   [2]     chr1     61-89      *
#   [3]     chr1   106-110      *
#   -------
#   seqinfo: 2 sequences from an unspecified genome; no seqlengths
```
Note that removing the portions of any range in `input` that overlap the ranges in `filter` tends to fragment any given range in input into smaller pieces. Since these pieces cannot be represented with a single range, it's natural to represent the result with a GRangesList object instead of a GRanges object. This GRangesList object is _parallel_ to `input` i.e. it has one list element per range in `input`.

OK I understand that all of this might be a little bit confusing and, in hindsight, maybe `setdiff(x, y)` should have been doing something like `x[!(x %in% y)]` which is what it does on atomic vectors in base R. The `union()`, `intersect()`, and `setdiff()` methods for IRanges objects were introduced a long time ago (in 2008, see https://github.com/Bioconductor/IRanges/commit/79277c57da68604262283269501541a109259281), and, at the time, treating the input objects as sets of _positions_ seemed like the most useful semantic, even though it's not consistent with the semantic of `==` and `%in%` on IRanges or GRanges objects. Changing this now would be extremely disruptive.

Finally please note that this kind of question is better asked on the [Bioconductor support site](https://support.bioconductor.org).

Best,
H.

**Comment by gevro** [comment]
Thank you very much. This makes sense. I do think the documentation could be more clear on this at least, and possibly adding a function that would do the behavior I described. 
i.e. the solution you gave with: psetdiff(input, rep(GRangesList(filter), length(input))), or even better:
unlist(psetdiff(input, rep(GRangesList(filter), length(input))))

i.e.:
subtractGRanges <- function(gr1,gr2){
unlist(psetdiff(gr1, rep(GRangesList(gr2), length(gr1))))
}

But also note that I suspect this would be very memory inefficient. If gr1 and gr2 are large, it requires making the GRangesList duplicating gr2 by the length of gr1.

The only other solution I found, which works, was written by bosberg here, using bedtoolsr
https://www.biostars.org/p/489350/
```
library(GenomicRanges)
library(bedtoolsr)
# Written by bosberg on Biostars, March 22, 2021. Free to use for scholarly purposes.

GRanges_subtract <- function( gr1, gr2 )
{
  # Subtract GRange object gr2 from gr1, but unlike setdiff, preserve individual
  # ranges in gr1
  df_1 = data.frame( seqnames=seqnames(gr1), start=start(gr1)-1, end=end(gr1), strand=strand(gr1), mcols( gr1 ) )
  df_2 = data.frame( seqnames=seqnames(gr2), start=start(gr2)-1, end=end(gr2), strand=strand(gr2), mcols( gr2 ) )
  #                                                          ^ -1 --> convert to base-0 start for bedtools
  result = bedtoolsr::bt.subtract(df_1, df_2)

  if ( length(result)==0 ){
    # subtraction has left nothing remaining. Return empty GRanges obj.
    return( GRanges() )
  } else {

    colnames( result ) = colnames( df_1 )
    result$start=result$start+1
    #                        ^ reset to base-1 notation consistent with GRanges

    return ( GRanges( result ) )
  }
}
```

**Comment by hpages** [comment]
Well, now that we know exactly what behavior you are after, we can focus on speed, and also add a few more functionalities (e.g. support for `ignore.strand` and propagation of the names and metadata columns):
```
library(GenomicRanges)

GRanges_subtract2 <- function(gr1, gr2, ignore.strand=FALSE)
{
    gr2 <- reduce(gr2, ignore.strand=ignore.strand)
    hits <- findOverlaps(gr1, gr2, ignore.strand=ignore.strand)
    ans <- psetdiff(gr1, extractList(gr2, as(hits, "IntegerList")))
    unlisted_ans <- unlist(ans, use.names=FALSE)
    mcols(unlisted_ans) <- extractROWS(mcols(gr1),
                                       Rle(seq_along(ans), lengths(ans)))
    setNames(relist(unlisted_ans, ans), names(gr1))
}
```

Then:
```
input <- GRanges(c(A="chr1:1-50", B="chr1:100-150", C="chr1:40-110"))
filter <- GRanges(c("chr1:11-20", "chr1:90-105", "chrM:1-10", "chr1:55-60"))

GRanges_subtract2(input, filter)
# GRangesList object of length 3:
# $A
# GRanges object with 2 ranges and 0 metadata columns:
#       seqnames    ranges strand
#          <Rle> <IRanges>  <Rle>
#   [1]     chr1      1-10      *
#   [2]     chr1     21-50      *
#   -------
#   seqinfo: 2 sequences from an unspecified genome; no seqlengths
# 
# $B
# GRanges object with 1 range and 0 metadata columns:
#       seqnames    ranges strand
#          <Rle> <IRanges>  <Rle>
#   [1]     chr1   106-150      *
#   -------
#   seqinfo: 2 sequences from an unspecified genome; no seqlengths
# 
# $C
# GRanges object with 3 ranges and 0 metadata columns:
#       seqnames    ranges strand
#          <Rle> <IRanges>  <Rle>
#   [1]     chr1     40-54      *
#   [2]     chr1     61-89      *
#   [3]     chr1   106-110      *
#   -------
#   seqinfo: 2 sequences from an unspecified genome; no seqlengths
```

Compared to the bedtools-based solution:
```
GRanges_subtract(input, filter)
# GRanges object with 6 ranges and 0 metadata columns:
#       seqnames    ranges strand
#          <Rle> <IRanges>  <Rle>
#   [1]     chr1      1-10      *
#   [2]     chr1     21-50      *
#   [3]     chr1   106-150      *
#   [4]     chr1     40-54      *
#   [5]     chr1     61-89      *
#   [6]     chr1   106-110      *
#   -------
#   seqinfo: 1 sequence from an unspecified genome; no seqlengths

unlist(GRanges_subtract2(input, filter))
# GRanges object with 6 ranges and 0 metadata columns:
#     seqnames    ranges strand
#        <Rle> <IRanges>  <Rle>
#   A     chr1      1-10      *
#   A     chr1     21-50      *
#   B     chr1   106-150      *
#   C     chr1     40-54      *
#   C     chr1     61-89      *
#   C     chr1   106-110      *
#   -------
#   seqinfo: 2 sequences from an unspecified genome; no seqlengths
```
Same results, but the raw output of `GRanges_subtract2()` is a GRangesList object _parallel_ to its first argument which a more structured output.

Speed:
```
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
input <- transcripts(txdb)
filter <- cds(txdb)
length(input)
# [1] 258145
length(filter)
# [1] 306369

system.time(res1 <- GRanges_subtract(input, filter))
#    user  system elapsed 
#  18.461   0.327  18.794

## GRanges_subtract() always ignores the strand so we set 'ignore.strand' to TRUE to mimic
## its behavior:
system.time(res2 <- GRanges_subtract2(input, filter, ignore.strand=TRUE))
#    user  system elapsed 
#   0.649   0.008   0.657 
```
`GRanges_subtract2()` is about 28x faster than `GRanges_subtract()`!

Sanity check:
```
## GRanges_subtract() does not preserve the original seqinfo (it drops the seqlevels that
## are not represented in the result) so we "fix" that:
seqlevels(res1) <- seqlevels(input)
seqinfo(res1) <- seqinfo(input)

## Then:
identical(res1, unlist(res2))
# [1] TRUE
```

Cheers,
H.

**Comment by gevro** [comment]
Amazing! This would be a really useful function to add to GenomicRanges. Thank you!

**Comment by hpages** [comment]
Done. See commit b2a4193591c465602fbe2a6a99308d99820e2cba

H.
