### ISSUE TITLE
drop.self and drop.redundant for Genomic Ranges

### ISSUE THREAD

**Issue by DarioS** [Bioconductor/GenomicRanges#71]
At the risk of reviving others' decade-old request, could the same options as for IRanges be supported for genomic ranges too?

**Comment by hpages** [comment]
With no context at all, it's impossible to know what you are talking about. What function? What decade-old request? What's your use case? What have you tried? MRE? `sessionInfo()`? Thank you

**Comment by DarioS** [comment]
Oh, I was referring to [Janet Young's request](https://support.bioconductor.org/p/60039/) of avoiding all of the self hits when there is only one input to `findOverlaps`. For `IRanges`, `findOverlaps` has `...` which allows `drop.self` and `drop.redundant` but the GRanges variety does not have ellipsis and so it does not allow such parameters to be set by the end user. Worthwhile or not to harmonise?

**Comment by hpages** [comment]
This request from Janet Young is more than 8 years old. A few things happened in the meantime. Did you bother to try `findOverlaps()` on a GRanges object with `drop.self=TRUE` and/or `drop.redundant=TRUE`, and using a reasonably recent version of Bioconductor? If that doesn't work, then please reopen this issue and I apologize in advance.
