### ISSUE TITLE
reduce documentation

### ISSUE THREAD

**Issue by gevro** [Bioconductor/GenomicRanges#85]
Hi, It seems that the reduce function outputs a sorted output, but this is not documented. Just confirming that this is indeed what happens? If so, might be useful to document this. Thanks

**Comment by hpages** [comment]
Yes the ouput is sorted. This is documented in `?IRanges::reduce`:
```
  reduce:

       ‘reduce’ first orders the ranges in ‘x’ from left to right, then
       merges the overlapping or adjacent ones.
```
This is in the **IRanges** package. The man page for `reduce()` in **GenomicRanges** (`?GenomicRanges::reduce`) refers the reader to the man page in **IRanges** for the full details.

Hope this helps,

H.

**Comment by gevro** [comment]
Thanks!
